### PR TITLE
Add two regular events

### PR DESCRIPTION
**Pull request by ppapadeas**

### CODE REVIEW

**Comment by comzeradd** [comment]
I don't think we want to do it this way. It doesn't scale that good if we start hardcoding everything there and it has the problem of implying that the hackerspace is open even when the meeting doesn't take place. We would also need to differentiate regular events from project meetings.

The best way is to find a way to have recurring events on the wiki. I think @SotiriosVrachas is already working on that.

**Comment by SotiriosVrachas** [comment]
The plan is to have an events form in Panopticon that resembles the UI of Mozilla Sunbird's > New Event > Repeat > Custom, for weekly and monthly events.

**Comment by SotiriosVrachas** [comment]
Semantic MediaWiki has a recurring event function. I tested the examples but currently it dose not work in our wiki. We should look into fixing this. https://www.semantic-mediawiki.org/wiki/Help:Recurring_events

Currently I see no reason not to merge this commit.

**Comment by comzeradd** [comment]
Well, these recurring events don't take place any more. So I'll close this and I'll open a ticket for infra to look into this wiki plugin.

**Pull request closed without merging**
